name: Build and Publish Image

on:
  push:
    paths-ignore:
      - '**/*.md'
    branches:
      - 'main'
  release:
    types:
      - released

jobs:
    build-and-push-latest:
      if: ${{ github.ref == 'refs/heads/main' }}
      runs-on: ohioit
      permissions:
        contents: read
        packages: write
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Log in to the Container registry
          uses: docker/login-action@v3.3.0
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Build necessary docker images
          uses: hiberbee/github-action-skaffold@1.27.0
          with:
            skaffold-version: 1.39.1
            container-structure-test-version: 1.11.0
            command: build
            push: true
            cache: true
            tag: latest

    build-and-push-release:
      if: ${{ github.ref != 'refs/heads/main' }}
      runs-on: ohioit
      permissions:
        contents: read
        packages: write
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Log in to the Container registry
          uses: docker/login-action@v3.3.0
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Build necessary docker images
          uses: hiberbee/github-action-skaffold@1.27.0
          with:
            skaffold-version: 1.39.1
            container-structure-test-version: 1.11.0
            command: build
            push: true
            cache: true
            tag: ${{ github.ref_name }}
