name: Build and Publish Image

on:
  push:
    paths-ignore:
      - '**/*.md'
    branches:
      - 'main'
      - 'cs/*'
  release:
    types:
      - released

jobs:
    build-and-push-latest:
      if: ${{ github.ref == 'refs/heads/main' }}
      runs-on: ohioit
      permissions:
        contents: read
        packages: write
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Kaniko build
          uses: aevea/action-kaniko@master
          with:
            registry: ghcr.io
            password: ${{ secrets.GITHUB_TOKEN }}
            tag: ${{ env.DOCKER_IMAGE_TAG }}
            cache: true
            cache_registry: cache

    build-and-push-branch:
      if: startsWith(github.ref, 'refs/heads/cs/')
      runs-on: ohioit
      permissions:
        contents: read
        packages: write
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - uses: docker/metadata-action@v3
          id: metadata
          with:
            images: ghcr.io/${{ github.repository }}
        - name: Determine tag name from branch name
          env:
            BRANCH_NAME: "${{ github.event.pull_request.head.ref }}"
          run: |
            echo "DOCKER_IMAGE_TAG::$(${BRANCH_NAME} | cut -d '/' -f 2)" >> $GITHUB_OUTPUT
        - name: Kaniko build
          uses: aevea/action-kaniko@master
          with:
            registry: ghcr.io
            password: ${{ secrets.GITHUB_TOKEN }}
            tag: ${{ env.DOCKER_IMAGE_TAG }}
            cache: true
            cache_registry: cache

    build-and-push-release:
      if: startsWith(github.ref, 'refs/tags/')
      runs-on: ohioit
      permissions:
        contents: read
        packages: write
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - uses: docker/metadata-action@v3
          id: metadata
          with:
            images: ghcr.io/${{ github.repository }}
        - name: Determine tag name from branch name
          env:
            TAG_NAME: "${{ github.event.pull_request.head.ref }}"
          run: |
            echo "DOCKER_IMAGE_TAG::$(${TAG_NAME} | cut -d '/' -f 3)" >> $GITHUB_OUTPUT
        - name: Kaniko build
          uses: aevea/action-kaniko@master
          with:
            registry: ghcr.io
            password: ${{ secrets.GITHUB_TOKEN }}
            tag: ${{ env.DOCKER_IMAGE_TAG }}
            cache: true
            cache_registry: cache

    delete-merged-docker-tags:
      if: ${{ github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'cs/') }}
      runs-on: ohioit
      permissions:
        contents: read
        packages: write
      steps:
        - name: Determine tag name from branch name
          env:
            BRANCH_NAME: "${{ github.event.pull_request.head.ref }}"
          run: |
            echo "::set-output name=DOCKER_IMAGE_TAG::$(${BRANCH_NAME} | cut -d '/' -f 2)"
        - name: Delete Docker tag
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            IMAGE_TAG: "${{ env.DOCKER_IMAGE_TAG }}"
          run: |
            TAG="${IMAGE_TAG}"
            REPO=ohioit/vscode-devcontainer-base
            curl -X DELETE \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              "https://ghcr.io/v2/${REPO}/manifests/${TAG}"
