name: Build and Publish Image

on:
  push:
    paths-ignore:
      - '**/*.md'
    branches:
      - 'main'
  release:
    types:
      - released

jobs:
    build-and-push-latest:
      if: ${{ github.ref == 'refs/heads/main' }}
      runs-on:
        - mw
      permissions:
        contents: read
        packages: write
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Log in to the Container registry
          uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Build necessary docker images
          # You may pin to the exact commit or the version.
          # uses: hiberbee/github-action-skaffold@390ff09081c63781da0e9eadd6b8506065f14fc7
          uses: hiberbee/github-action-skaffold@1.19.0
          with:
            skaffold-version: 1.39.1
            container-structure-test-version: 1.11.0
            command: build
            push: true
            cache: true
            tag: latest

    build-and-push-release:
      if: ${{ github.ref != 'refs/heads/main' }}
      runs-on:
        - mw
      permissions:
        contents: read
        packages: write
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Log in to the Container registry
          uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Build necessary docker images
          # You may pin to the exact commit or the version.
          # uses: hiberbee/github-action-skaffold@390ff09081c63781da0e9eadd6b8506065f14fc7
          uses: hiberbee/github-action-skaffold@1.19.0
          with:
            skaffold-version: 1.39.1
            container-structure-test-version: 1.11.0
            command: build
            push: true
            cache: true
            tag: ${{ github.ref_name }}
